remote_theme: volny/creative-theme-jekyll

# Site settings
title: Atishdev Choudhury
email: atish.choudhury@gmail.com
description: "Technology Enthusiast and Tinker"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: atishch
github_username: atishch

# Build settings
markdown: kramdown
